name: Deploy Active Content to Public Branch

defaults:
  run:
    shell: bash

permissions:
  contents: write

on:
  repository_dispatch:
    types: [deploy-public]
  workflow_dispatch:

jobs:
  publish-public-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean public folder
        run: |
          rm -rf public
          mkdir public

      - name: Copy all non-HTML public assets
        run: |
          find . -type f \( \
            -name '*.css' -o \
            -name '*.js' -o \
            -name '*.json' -o \
            -name '*.txt' -o \
            -name 'CNAME' \
          \) ! -path './.git/*' | while read filepath; do
            dir=$(dirname "$filepath")
            mkdir -p "public/$dir"
            cp "$filepath" "public/$filepath"
          done

      - name: Copy only active or draf
