name: Deploy Active Content to Public Branch

defaults:
  run:
    shell: bash
    
permissions:
  contents: write

on:
  repository_dispatch:
    types: [deploy-public]
  workflow_dispatch:  # Optional: for manual triggering

jobs:
  publish-public-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean public folder
        run: |
          rm -rf public
          mkdir public

      - name: Copy all non-HTML assets to public/
        run: |
          find . -type f ! -path './.git/*' ! -path './.github/*' ! -path './public/*' \
                 ! -path './.*' ! -name '*.html' | while read filepath; do
            dir=$(dirname "$filepath")
            mkdir -p "public/$dir"
            cp "$filepath" "public/$filepath"
          done

      - name: Don't copy inactive HTML files
        run: |
          find . -type f -name '*.html' ! -path './.git/*' ! -path './.github/*' ! -path './public/*' \
                 ! -path './.*' | while read file; do
            pattern="(content)\\s*=\\s*[\"']inactive[\"']"
            if grep -Pi "$pattern" "$file"; then
              echo "Skipping inactive file: $file"
              continue
            fi
            dir=$(dirname "$file")
            mkdir -p "public/$dir"
            cp "$file" "public/$file"
            echo "Included: $file"
          done

      - name: Switch to public branch and clean all old files
        run: |
          git fetch origin public || true
          git checkout public || git checkout -b public

          # Wipe all tracked and untracked files
          git rm -rf . || true
          git clean -fdx

      - name: Copy new public content to branch root
        run: |
          cp -r public/* ./
          rm -rf public

      - name: Configure Git identity
        run: |
          git config user.name "WFE Bot"
          git config user.email "trustee@williamsfamilyestate.org"

      - name: Commit and push to public
        run: |
          git add .
          git commit -m "Deploy active content to public branch" || echo "No changes to commit"
          git push origin HEAD:public --force
