name: Deploy Active Content to Public Branch

defaults:
  run:
    shell: bash

permissions:
  contents: write

on:
  repository_dispatch:
    types: [deploy-public]
  workflow_dispatch:

jobs:
  publish-public-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (if needed)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create temp public staging folder
        run: mkdir -p /tmp/public

      - name: Copy all non-HTML assets to /tmp/public
        run: node .github/scripts/utils/copy-files.js assets /tmp/public

      - name: Copy only active HTML files to /tmp/public
        run: node .github/scripts/utils/copy-files.js html /tmp/public

      - name: Copy site-config.json to public folder
        run: cp site-config.json /tmp/public/
        
      - name: Audit staged public content
        run: |
          echo "Public content staged at /tmp/public:"
          tree /tmp/public || find /tmp/public
          echo ""
          echo "File count:"
          find /tmp/public -type f | wc -l
      
          if [ $(find /tmp/public -type f | wc -l) -eq 0 ]; then
            echo "No files staged for deployment. Aborting to prevent blank commit."
            exit 1
          fi

      - name: Switch to public branch and clean all old files
        run: |
          git fetch origin public || true
          git checkout public || git checkout -b public
          git rm -rf . || true
          git clean -fdx

      - name: Copy new public content to branch root
        run: cp -r /tmp/public/* ./

      - name: Configure Git identity
        run: |
          git config user.name "WFE Bot"
          git config user.email "trustee@williamsfamilyestate.org"

      - name: Commit and push to public
        run: |
          git add .
          git commit -m "Deploy active content to public branch" || echo "No changes to commit"
          git push origin HEAD:public --force
