name: Deploy Active Content to Public Branch

defaults:
  run:
    shell: bash

permissions:
  contents: write

on:
  repository_dispatch:
    types: [deploy-public]
  workflow_dispatch:  # Optional: for manual triggering

jobs:
  publish-public-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean public folder
        run: |
          rm -rf public
          mkdir public

      - name: Copy all non-HTML public assets
        run: |
          find . -type f \( \
            -name '*.css' -o \
            -name '*.js' -o \
            -name '*.json' -o \
            -name '*.txt' -o \
            -name 'CNAME' \
          \) ! -path './.git/*' | while read filepath; do
            dir=$(dirname "$filepath")
            mkdir -p "public/$dir"
            cp "$filepath" "public/$filepath"
          done

      - name: Copy only active HTML files
        run: |
          for file in $(find . -type f -name '*.html' ! -path './.git/*'); do
            if grep -Pi 'content\s*=\s*["'\'']inactive["'\'']' "$file"; then
              echo "Skipping inactive: $file"
              continue
            fi
            dir=$(dirname "$file")
            mkdir -p "public/$dir"
            cp "$file" "public/$file"
            echo "Included: $file"
          done

      - name: Switch to public branch and clean old content
        run: |
          git fetch origin public || true
          git checkout public || git checkout -b public
          git rm -rf . || true
          git clean -fdx

      - name: Copy new content to root of public branch
        run: |
          cp -r public/* ./
          rm -rf public

      - name: Configure Git identity
        run: |
          git config user.name "WFE Bot"
          git config user.email "trustee@williamsfamilyestate.org"

      - name: Commit and push public content
        run: |
          git add .
          git commit -m "Deploy active content to public branch" || echo "No changes to commit"
          git push origin HEAD:public --force
