name: Deploy Active Content to Public Branch

permissions:
  contents: write

on:
  push:
    branches:
      - master
    paths:
      - '**/*'
  workflow_dispatch:

jobs:
  publish-public-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean public folder
        run: |
          rm -rf public
          mkdir public

      - name: Copy all non-HTML assets to public/
        run: |
          find . -type f ! -name '*.html' | while read filepath; do
            dir=$(dirname "$filepath")
            mkdir -p "public/$dir"
            cp "$filepath" "public/$filepath"
          done

      - name: Copy only active HTML files
        run: |
          for file in $(find . -type f -name '*.html'); do
            base=$(basename "$file")
            dir=$(dirname "$file")

            # Skip templates and index
            if [[ "$base" == *_template.html || "$base" == index.html ]]; then continue; fi

            # If the file is marked inactive, skip it
            if grep -iq '<meta[^>]*name=["'\''"]doc-status["'\''"][^>]*content=["'\''"]inactive["'\''"]' "$file"; then
              echo "Skipping inactive file: $file"
              continue
            fi

            mkdir -p "public/$dir"
            cp "$file" "public/$file"
          done

      - name: Configure Git identity
        run: |
          git config user.name "WFE Bot"
          git config user.email "trustee@williamsfamilyestate.org"

      - name: Switch to public branch
        run: |
          git fetch origin public || git checkout --orphan public
          git checkout public || git checkout -b public
          git reset --hard

      - name: Move filtered output into working root
        run: |
          mkdir staging
          cp -r public/* staging/
          rm -rf *
          cp -r staging/* ./
          rm -rf staging public

      - name: Commit and push to public
        run: |
          git add .
          git commit -m "Deploy active content to public branch" || echo "No changes to commit"
          git push origin HEAD:public --force
