name: Auto-generate Manifest Files

permissions:
  contents: write

on:
  push:
    branches:
      - master
    paths:
      - '**/*.html'
  workflow_dispatch:

jobs:
  generate-manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Discover template folders
        id: discover
        run: |
          echo "folders=[]" >> $GITHUB_ENV
          FOLDERS=$(find . -type f -name '*_template.html' | sed -E 's|\./([^/]+)/[^/]+_template.html|\1|' | sort -u)
          echo "Found folders: $FOLDERS"
          echo "folders=[$(echo $FOLDERS | sed 's/ /,/g')]" >> $GITHUB_ENV

      - name: Generate manifests
        run: |
          for folder in $(find . -type f -name '*_template.html' | sed -E 's|\./([^/]+)/[^/]+_template.html|\1|' | sort -u); do
            TEMPLATE_FILE="${folder}_template.html"
            echo "Generating manifest for: $folder"
            echo "[" > "$folder/manifest.json"
            FIRST=true
            for file in $folder/*.html; do
              base=$(basename "$file")
              if [[ "$base" != "index.html" && "$base" != "$TEMPLATE_FILE" ]]; then
                MODIFIED=$(date -Iseconds -r "$file")
                if [ "$FIRST" = false ]; then echo "," >> "$folder/manifest.json"; fi
                echo "  {\"filename\": \"$base\", \"lastModified\": \"$MODIFIED\"}" >> "$folder/manifest.json"
                FIRST=false
              fi
            done
            echo "]" >> "$folder/manifest.json"
          done

      - name: Configure Git identity
        run: |
          git config user.name "WFE Bot"
          git config user.email "trustee@williamsfamilyestate.org"

      - name: Force set origin to use PAT
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.WFE_AUTOPUSH_TOKEN }}@github.com/${{ github.repository }}

      - name: Commit and push updated manifests
        run: |
          git fetch origin master
          git add */manifest.json
          git commit -m "Auto-update manifest.json for all folders" || echo "No changes to commit"
          git push origin HEAD:master
