name: Auto-generate Manifests and Metadata Stubs

permissions:
  contents: write

on:
  push:
    branches:
      - master
    paths:
      - '**/*.html'
      - '.github/scripts/**'
      - '.github/workflows/update-manifest.yml'
  workflow_dispatch:

jobs:
  update-site-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install cheerio --no-save

      - name: Generate CSS Metadata Stubs
        run: node .github/scripts/generate-css-stubs.js

      - name: Generate Manifest Files and QR Routes
        run: node .github/scripts/generate-manifests.js

      - name: Configure Git identity
        run: |
          git config user.name "WFE Bot"
          git config user.email "trustee@williamsfamilyestate.org"

      - name: Commit and push updated manifests and styles
        run: |
          git fetch origin master
          git add **/*.json **/style.css
          git commit -m "Auto-update metadata CSS stubs, json manifests, and QR routes" || echo "No changes to commit"
          git push origin HEAD:master

  trigger-deploy:
    needs: update-site-data
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy-public workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.WFE_AUTOPUSH_TOKEN }}
          repository: ${{ github.repository }}
          event-type: deploy-public
