name: Auto-generate Manifest Files

permissions:
  contents: write
  packages: read
  issues: read
  pull-requests: read

on:
  push:
    branches:
      - master
    paths:
      - 'notices/*.html'
      - 'emergency/*.html'
  workflow_dispatch:

jobs:
  build-manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate notices manifest
        run: |
          if compgen -G "notices/*.html" > /dev/null; then
            echo "HTML files found in notices/, generating manifest..."
            mkdir -p .github/actions/build-manifest/temp
            cp -r .github/actions/build-manifest/* .github/actions/build-manifest/temp/
            chmod +x .github/actions/build-manifest/temp/action.yml
            echo "Using composite action"
          else
            echo "No notice HTML files found. Skipping manifest generation."
            exit 0
          fi

      - name: Generate notices manifest
        if: ${{ success() }}
        uses: ./.github/actions/build-manifest
        with:
          folder: notices
          template_ignore: Notice_Template.html

- name: Generate emergency manifest
        run: |
          if compgen -G "emergency/*.html" > /dev/null; then
            echo "HTML files found in emergency/, generating manifest..."
          else
            echo "No emergency HTML files found. Skipping manifest generation."
            exit 0
          fi

      - name: Generate emergency manifest
        if: ${{ success() }}
        uses: ./.github/actions/build-manifest
        with:
          folder: emergency
          template_ignore: Emergency_Template.html

- name: Configure Git identity
        run: |
          git config user.name "WFE Bot"
          git config user.email "trustee@williamsfamilyestate.org"

      - name: Force set origin to use PAT
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.WFE_AUTOPUSH_TOKEN }}@github.com/${{ github.repository }}

      - name: Commit and push updated manifests
        run: |
          git fetch origin master
          if [ -f notices/manifest.json ]; then git add notices/manifest.json; fi
          if [ -f emergency/manifest.json ]; then git add emergency/manifest.json; fi
          git commit -m "Auto-update manifests" || echo "No changes to commit"
          git push origin HEAD:master
