name: Auto-generate Notice Manifest

on:
  push:
    paths:
      - 'notices/*.html'
  workflow_dispatch:

jobs:
  build-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - show working directory
        run: |
          echo "Working directory:"
          pwd
          ls -al

      - name: Generate manifest.json from notice files
        run: |
          ls notices/*.html | xargs -n1 basename | jq -R -s -c 'split("\n") | map(select(. != ""))' > notices/manifest.json
          cat notices/manifest.json

      - name: Confirm interpolated push URL
        run: echo "https://x-access-token:${{ secrets.WFE_AUTOPUSH_TOKEN }}@github.com/${{ github.repository }}" | sed 's/x-access-token:.*/x-access-token:***@github.com/'

      - name: Confirm git remote from correct directory
        run: |
          cd $GITHUB_WORKSPACE
          git remote -v

      - name: Commit and push updated manifest
        run: |
          cd $GITHUB_WORKSPACE
          git config user.name "AutoBot"
          git config user.email "autobot@williamsfamilyestate.org"
          git add notices/manifest.json
          git commit -m "Auto-update manifest.json" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.WFE_AUTOPUSH_TOKEN }}@github.com/${{ github.repository }} HEAD:main
