name: Auto-generate Notice Manifest

on:
  push:
    paths:
      - 'notices/*.html'
  workflow_dispatch:

jobs:
  build-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - show current folder contents
        run: |
          echo "Current directory:"
          pwd
          echo "List of files:"
          ls -al

      - name: Generate manifest.json from notice files
        run: |
          cd notices
          ls *.html | jq -R -s -c 'split("\n") | map(select(. != ""))' > manifest.json
          echo "Generated manifest.json:"
          cat manifest.json

      - name: Set up Git auth with token
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.WFE_AUTOPUSH_TOKEN }}@github.com/${{ github.repository }}

      - name: Commit and push updated manifest
        run: |
          git config user.name "AutoBot"
          git config user.email "autobot@williamsfamilyestate.org"
          git add notices/manifest.json
          git commit -m "Auto-update manifest.json" || echo "No changes to commit"
          git push origin HEAD:main
