name: Auto-generate site structure, manifest files, metadata stubs, CSS styles, etc

defaults:
  run:
    shell: bash
    
permissions:
  contents: write

on:
  push:
    branches:
      - master
    paths:
      - '**/*.html'
      - 'site-config.json'
      - '.github/scripts/**'
      - '.github/workflows/update-manifest.yml'
  workflow_dispatch:

jobs:
  update-site-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install script dependencies (postcss cheerio + glob + node-fetch)
        working-directory: .github/scripts
        run: npm install postcss postcss-safe-parser cheerio glob node-fetch@2 --no-save
        #run: npm install cheerio glob node-fetch@2 --no-save

      - name: Generate Manifest Files and QR Routes
        run: node .github/scripts/generate-manifests.js

      - name: Maintain Styles (stubs, distribute, inject, clean)
        run: node .github/scripts/maintain-styles.js all

      - name: Generate sitemap.xml
        run: node .github/scripts/generate-sitemap.js

      - name: Generate Page Routes
        run: node .github/scripts/generate-clean-path-redirects.js

      - name: Sync up any direct link PDF files (PDF filename = HTML)
        run: node .github/scripts/sync-pdf-links.js
        
      - name: Strip BOM from HTML files
        run: |
          find . -type f -name '*.html' -exec sed -i '1s/^\xEF\xBB\xBF//' {} \;

      - name: Archive active documents to Archive.org
        run: node .github/scripts/webarchive-active-pages.js

      - name: Configure Git identity
        run: |
          git config user.name "WFE Bot"
          git config user.email "trustee@williamsfamilyestate.org"

      - name: Commit and push updated manifests and styles
        run: |
          git add */ */*/ */*/*.html */*.json */*.css */*.txt sitemap.xml CNAME *.js scripts/**/*.js .github/**/*.yml
          git commit -m "Auto-update site metadata, page routes, manifests, and style maintenance"
          git pull
          git push origin HEAD:master

  trigger-deploy:
    needs: update-site-data
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy-public workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.WFE_AUTOPUSH_TOKEN }}
          repository: ${{ github.repository }}
          event-type: deploy-public
