name: Auto-generate Manifest Files

permissions:
  contents: write
  packages: read
  issues: read
  pull-requests: read

on:
  push:
    branches:
      - master
    paths:
      - 'notices/*.html'
      - 'emergency/*.html'
  workflow_dispatch:

jobs:
  build-manifests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate notices manifest
        uses: ./.github/actions/build-manifest
        with:
          folder: notices
          template_ignore: Notice_Template.html

      - name: Generate emergency manifest
        uses: ./.github/actions/build-manifest
        with:
          folder: emergency
          template_ignore: Emergency_Template.html

      - name: Configure Git identity
        run: |
          git config user.name "WFE Bot"
          git config user.email "trustee@williamsfamilyestate.org"

      - name: Force set origin to use PAT
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.WFE_AUTOPUSH_TOKEN }}@github.com/${{ github.repository }}

      - name: Commit and push updated manifests
        run: |
          git fetch origin master
          
          if [ -f notices/manifest.json ]; then
            echo "Adding notices manifest"
            git add notices/manifest.json
          else
            echo "⚠️ No notices manifest found"
          fi
          
          if [ -f emergency/manifest.json ]; then
            echo "Adding emergency manifest"
            git add emergency/manifest.json
          else
            echo "⚠️ No emergency manifest found"
          fi

          git commit -m "Auto-update manifests" || echo "No changes to commit"
          git push origin HEAD:master
