name: Auto-generate Notice Manifest

permissions:
  contents: write
  
on:
  push:
    paths:
      - 'notices/*.html'
  workflow_dispatch:

jobs:
  build-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate manifest.json from notice files (with lastModified)
        run: |
          cd notices
          echo "[" > manifest.json
          FIRST=true
          for f in *.html; do
            if [[ "$f" != "index.html" && "$f" != "Notice_Template.html" ]]; then
              # Get last commit timestamp for this file (ISO 8601 format)
              MODIFIED=$(git log -1 --format="%cI" -- "$f" || echo "$(date -Iseconds)")
              if [ "$FIRST" = false ]; then echo "," >> manifest.json; fi
              echo "  {\"filename\": \"$f\", \"lastModified\": \"$MODIFIED\"}" >> manifest.json
              FIRST=false
            fi
          done
          echo "]" >> manifest.json
          echo "Generated manifest.json:"
          cat manifest.json
    
      - name: Configure Git identity
        run: |
          git config user.name "WFETrustee Auto"
          git config user.email "trustee@williamsfamilyestate.org"

      - name: Force set origin to use PAT
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.WFE_AUTOPUSH_TOKEN }}@github.com/${{ github.repository }}

      - name: Commit and push updated manifest
        run: |
          cd $GITHUB_WORKSPACE
          git add notices/manifest.json
          git commit -m "Auto-update manifest.json with lastModified timestamps" || echo "No changes to commit"
          git fetch origin master
          git reset --hard origin/master
          git push origin HEAD:master


